### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by gerard33** [thomasloven/lovelace-fullykiosk#1]
Thanks for this great piece of software!

Using this together with [Lovelace kiosk](https://gist.github.com/ciotlosm/1f09b330aa5bd5ea87b59f33609cc931#keep-tabs) gives the option to only show one tab of HA without having the option to go to the menu or other tabs. And that's a great use case for a wall mounted tablet.

I have some feature requests which are all supported by the JS interface of Fully.

1. Add start or stop motion detection.
This way depending if you are at home or not you can set the motion detection, so it will only work when you are at home and not when e.g. the cleaner is the only one at home.
2. Add TTS functionality.
3. Add screensaver functionality.
4. Add play video functionality. So when the doorbell is being pressed the frontdoor camera pops up automatically.
5. Add bring to foreground functionality.

Some useful information is available in the [Tileboard Github](https://github.com/resoai/TileBoard#events) as well.

Just let me know what you think. I can have a look at this myself as well, but have only little knowledge of JS, so will take me a lot of trial and error :grinning:

**Comment by thomasloven** [comment]
1: This is better handled from home-assistant. If motion is triggered at a time when you don't care - just ignore it.
2: See [lovelace-player](https://github.com/thomasloven/lovelace-player). This lets you use any of home-assistants available tts methods, not just google.
4: This could be done within lovelace with the new conditional card
3 and 5 can be implemented just as well using the REST interface. Having them in lovelace-fullykiosk brings no advantages such as the improved speed in motion detection.

**Comment by gerard33** [comment]
1. I should have explained this one better :wink:
I want to use the motion detection function so it automatically shows the Lovelace screen on the tablet on motion. But don't want that function to be on when I am not at home.
For this you can use `fully.startMotionDetection()` and `fully.stopMotionDetection()`.
So it's not for handling the triggers in HA, but to turn the screen of the tablet on.

Solution can be to add a boolean to HA which can control the motion detection function of Fully on the tablet.

Will have a look at your other points.

**Comment by thomasloven** [comment]
This could also be handled just as well with the REST interface
`/?cmd=setBooleanSetting&key=motionDetection&value=true|false&password=`

Or you could controll the screen on/off on motion entirely from home-assistant and turn the "Turn Screen On on Motion" setting off permanently.

**Comment by thomasloven** [comment]
I must admit there is one advantage with having the settings in this plugin, though. You don't need to know the IP of the device.

**Comment by gerard33** [comment]
> Or you could controll the screen on/off on motion entirely from home-assistant and turn the "Turn Screen On on Motion" setting off permanently.

I have added a switch in HA using the REST interface for this.
`/?cmd=setBooleanSetting&key=screenOnOnMotion&value=true&password=`

Only issue I have is that despite setting this to False (even in the settings of the app), the screen still turns on when motion is detected.
My idea was to set this only to True only when I am home, so I can use the tablet as motion detection, but for some strange reason that setting doesn't work as it should.

Also added switch in HA using the REST interface for the screensaver and bring to foreground.
That works great indeed. Thanks for these tips.

**Comment by gerard33** [comment]
4: from the HA forum I got the following command for the REST interface to popup the camera
`?type=json&cmd=loadURL&url=javascript:document.querySelector('home-assistant').shadowRoot.querySelector('home-assistant-main').fire('hass-more-info',{entityId:'camera.camera_name'})&password=`
Where you replace camera_name.

And close the camera with
`?type=json&cmd=loadURL&url=javascript:document.querySelector('home-assistant').shadowRoot.querySelector('home-assistant-main').fire('hass-more-info',{entityId:null})&password=`

**Comment by IsaacBreuer** [comment]
Any fix on this motion detection enable/disable?
I have a requirement not to have motion on on some days (shabbat) and on for the rest of the week. Doing true HA is not an option as it will still trigger but ignored in HA . I want not to triger at all
