### ISSUE TITLE
dashboard_screen and dashboard_motion dont work on 0.84.6

### ISSUE THREAD

**Issue by plantoschka** [thomasloven/lovelace-fullykiosk#2]
Hi,

just installed and configured this wonderful addon. But it doesn't really work. I see the sensors but motion and screen don't get updated. When I trigger screen on/off nothing happens. No messages in the log. I also don't get the battery percentage.

The camera works fine.

Can anyone confirm if this still works in the new version of Home Assistant?

**Comment by ccmacaluso** [comment]
Mine is working. Perhaps your config file isn't properly pointing to the tablet? Do you have the correct ID in the config file?

**Comment by plantoschka** [comment]
Yeah the id is correct. Checked it three times.

**Comment by plantoschka** [comment]
Now it works. Looks like there were some permissions missing. After clicking on "Get All Runtime Permissions" it worked.
