### ISSUE TITLE
API Security?

### ISSUE THREAD

**Issue by TarheelGrad1998** [thomasloven/lovelace-fullykiosk#5]
Does this comply with the API security at all?  I've tried setting it up, but when I do it does not work, I get a slew of failled logins and Unauthorized messages.

**Comment by TarheelGrad1998** [comment]
A thought -- I created a new user for this purpose, and added them to the Users group (and not Administrators).  Do you know if users have access to the API?  

I could not find specific documentation on this, but when I get a chance I'll try again with the user as an Admin.

**Comment by TarheelGrad1998** [comment]
Yep, that was it.  Closing.

**Comment by thomasloven** [comment]
That's correct. Unfortunately this only works for an admin user.
I should add that to the documentation...
